# Generated by Django 2.2.5 on 2021-12-31 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_images', models.ImageField(upload_to='upload_images')),
                ('nation1', models.CharField(blank=True, max_length=20, null=True)),
                ('nation2', models.CharField(blank=True, max_length=20, null=True)),
                ('nation3', models.CharField(blank=True, max_length=20, null=True)),
                ('modified_nation', models.CharField(blank=True, max_length=20, null=True)),
                ('time_consuming', models.CharField(blank=True, max_length=50, null=True)),
                ('user_assess', models.CharField(blank=True, default='未填写', max_length=50, null=True)),
                ('user_update', models.CharField(blank=True, default='未修改', max_length=50, null=True)),
                ('user_change', models.CharField(blank=True, default='否', max_length=20, null=True)),
                ('user_propose', models.TextField(blank=True, default='未填写', max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
            ],
            options={
                'verbose_name': '识别结果',
                'verbose_name_plural': '识别结果',
                'ordering': ('-created',),
            },
        ),
    ]
